# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  BuildConfiguration: Release

trigger:
  branches:
    include:
    - master
    - develop
    - feature/*
  paths:
    include:
    - src/*
    - test/*
    - azure-pipelines.yml

stages:
- stage: Build
  jobs:
    - job: Build
      displayName: Build Artifacts
      pool:
        vmImage: 'ubuntu-latest'

      steps:
      - task: GitVersion@5
        displayName: 'GitVersion'
        inputs:
          updateAssemblyInfo: true
          preferBundledVersion: false

      - script: echo '%Action%%BuildVersion%'
        displayName: 'Set build version'
        env:
          Action: '##vso[build.updatebuildnumber]'
          BuildVersion: $(GitVersion.SemVer)

      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: '**/*[Tt]est*/*.csproj'
          arguments: '--configuration $(BuildConfiguration)'
      
      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack release'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: pack
          projects: '**/*.csproj'
          includesymbols: false
          outputDir: '$(Build.ArtifactStagingDirectory)'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'build-assets'
          targetPath: '$(Build.ArtifactStagingDirectory)'